"""
Intelligence Operating System — Agent Models
=============================================
ORM models for the agent orchestration domain:

``AgentTask``       — Top-level task submitted by a user. Drives the
                      LangGraph workflow from planning through to completion.
``AgentExecution``  — Per-agent execution record within a task. One row per
                      agent invocation; traces the complete multi-agent timeline.

Hierarchy:
    User  →  AgentTask  →  AgentExecution (many)

An ``AgentTask`` owns the high-level lifecycle and plan.
Each ``AgentExecution`` records what one specific agent did during that task —
its inputs, outputs, token usage, quality scores, and error details.

This separation enables:
- Task-level rollup metrics (total tokens, duration, success)
- Agent-level granular tracing (per-agent latency, quality)
- Replay: re-run individual agent steps with modified inputs
- Evaluation: compare agent quality across prompt versions

Cascade policy:
    AgentTask      → User         (cascade delete)
    AgentTask      → Conversation (SET NULL — task survives conversation deletion)
    AgentExecution → AgentTask    (cascade delete)
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum as SAEnum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.enums import AgentStatus, AgentType, TaskPriority, TaskStatus, WorkflowType
from app.models.base import AuditMixin, Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.conversation import Conversation
    from app.models.evaluation import Evaluation
    from app.models.memory import EpisodicMemory
    from app.models.tool import ToolExecution
    from app.models.user import User
    from app.models.workflow import Workflow


# ---------------------------------------------------------------------------
# AgentTask
# ---------------------------------------------------------------------------


class AgentTask(UUIDPrimaryKeyMixin, AuditMixin, Base):
    """
    A top-level unit of intelligent work submitted to IOS.

    An ``AgentTask`` progresses through ``TaskStatus`` states:
        PENDING → PLANNING → EXECUTING → [AWAITING_APPROVAL] → COMPLETE
                                                              → FAILED
                                                              → CANCELLED

    The task owns the execution plan (stored in ``Workflow``) and
    aggregates quality metrics from all child ``AgentExecution`` records.

    Human-in-the-loop:
        ``requires_approval`` flag marks tasks where the user must review
        the plan or each step before execution proceeds.
        ``approval_status`` tracks the current gate state.
    """

    __tablename__ = "agent_tasks"
    __table_args__ = (
        Index("ix_agent_tasks_user_id", "user_id"),
        Index("ix_agent_tasks_status", "status"),
        Index("ix_agent_tasks_workflow_type", "workflow_type"),
        Index("ix_agent_tasks_priority", "priority"),
        Index("ix_agent_tasks_created_at", "created_at"),
        Index("ix_agent_tasks_conversation_id", "conversation_id"),
        {"comment": "Top-level intelligent task records driving LangGraph workflows."},
    )

    user_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    conversation_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("conversations.id", ondelete="SET NULL"),
        nullable=True,
        doc="Parent conversation (NULL for API-submitted tasks without a session).",
    )
    # Task description
    title: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        doc="Short title auto-generated by the Planner or set by the user.",
    )
    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="Full natural-language task description submitted by the user.",
    )
    intent: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        doc="Classified intent (e.g. 'code_generation', 'data_analysis').",
    )
    # Lifecycle
    status: Mapped[TaskStatus] = mapped_column(
        SAEnum(TaskStatus, name="task_status_enum", create_type=True),
        nullable=False,
        default=TaskStatus.PENDING,
        server_default=text("'pending'"),
    )
    workflow_type: Mapped[WorkflowType] = mapped_column(
        SAEnum(WorkflowType, name="workflow_type_enum", create_type=True),
        nullable=False,
        default=WorkflowType.GENERAL,
        server_default=text("'general'"),
    )
    priority: Mapped[TaskPriority] = mapped_column(
        SAEnum(TaskPriority, name="task_priority_enum", create_type=True),
        nullable=False,
        default=TaskPriority.NORMAL,
        server_default=text("'5'"),
    )
    # Timing
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    duration_ms: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        doc="Wall-clock duration from start to completion in milliseconds.",
    )
    # Token accounting
    total_prompt_tokens: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
    )
    total_completion_tokens: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
    )
    total_tokens: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
    )
    # Human-in-the-loop
    requires_approval: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        doc="True if this task requires human approval at plan and/or action gates.",
    )
    approval_status: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        doc="Current HITL gate status: 'pending', 'approved', 'rejected'.",
    )
    approval_notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Human operator notes provided at approval gate.",
    )
    # Quality aggregates (rolled up from child AgentExecutions)
    overall_quality_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        doc="Aggregate quality score across all agent executions (0.0–1.0).",
    )
    hallucination_detected: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        doc="True if any agent output was flagged by hallucination detection.",
    )
    # Output
    final_output: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="The synthesised final response to the user.",
    )
    error_message: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Error detail if status is FAILED.",
    )
    error_code: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )
    # LangGraph state
    langgraph_run_id: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        doc="LangGraph run ID for checkpoint lookup.",
    )
    langgraph_thread_id: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        doc="LangGraph thread ID for stateful graph continuation.",
    )
    # MLflow tracking
    mlflow_run_id: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        doc="MLflow run ID for experiment tracking.",
    )
    # Prompt version snapshot
    prompt_versions: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'"),
        doc="Snapshot of prompt template versions used during this task.",
    )
    tags: Mapped[list[str]] = mapped_column(
        ARRAY(String),
        nullable=False,
        default=list,
        server_default=text("'{}'"),
    )
    extra_data: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'"),
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    user: Mapped["User"] = relationship("User", back_populates="tasks")
    conversation: Mapped["Conversation | None"] = relationship(
        "Conversation",
        back_populates="tasks",
    )
    executions: Mapped[list["AgentExecution"]] = relationship(
        "AgentExecution",
        back_populates="task",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="AgentExecution.started_at",
        doc="Per-agent execution records for this task.",
    )
    workflow: Mapped["Workflow | None"] = relationship(
        "Workflow",
        back_populates="task",
        uselist=False,
        cascade="all, delete-orphan",
        passive_deletes=True,
        doc="The execution plan workflow associated with this task.",
    )
    tool_executions: Mapped[list["ToolExecution"]] = relationship(
        "ToolExecution",
        back_populates="task",
        cascade="all, delete-orphan",
        passive_deletes=True,
        doc="All tool invocations triggered during this task.",
    )
    evaluations: Mapped[list["Evaluation"]] = relationship(
        "Evaluation",
        back_populates="task",
        cascade="all, delete-orphan",
        passive_deletes=True,
        doc="Evaluation runs attached to this task.",
    )
    episodic_memory: Mapped["EpisodicMemory | None"] = relationship(
        "EpisodicMemory",
        foreign_keys="EpisodicMemory.agent_task_id",
        uselist=False,
        doc="Experience record created from this task upon completion.",
    )

    def __repr__(self) -> str:
        return (
            f"<AgentTask id={self.id} status={self.status} "
            f"type={self.workflow_type} tokens={self.total_tokens}>"
        )


# ---------------------------------------------------------------------------
# AgentExecution
# ---------------------------------------------------------------------------


class AgentExecution(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """
    Execution record for a single agent invocation within an ``AgentTask``.

    One ``AgentExecution`` is created for each node execution in the LangGraph
    workflow.  This provides granular tracing of the multi-agent timeline:
    - Which agent ran
    - What inputs it received
    - What it produced
    - How long it took
    - How many tokens it consumed
    - What quality score it received from the Reflection Agent

    Retry attempts create new ``AgentExecution`` records (with ``retry_of``
    pointing to the original) rather than mutating the failed record.
    """

    __tablename__ = "agent_executions"
    __table_args__ = (
        Index("ix_agent_executions_task_id", "task_id"),
        Index("ix_agent_executions_agent_type", "agent_type"),
        Index("ix_agent_executions_status", "status"),
        Index("ix_agent_executions_started_at", "started_at"),
        Index("ix_agent_executions_step_index", "step_index"),
        {"comment": "Per-agent execution traces within a task workflow."},
    )

    task_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("agent_tasks.id", ondelete="CASCADE"),
        nullable=False,
    )
    retry_of: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("agent_executions.id", ondelete="SET NULL"),
        nullable=True,
        doc="If this is a retry, points to the original failed execution.",
    )
    step_index: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        doc="Zero-based step index within the task's execution plan.",
    )
    step_name: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
        doc="Human-readable step name from the execution plan.",
    )
    agent_type: Mapped[AgentType] = mapped_column(
        SAEnum(AgentType, name="agent_type_enum", create_type=True),
        nullable=False,
    )
    agent_instance_id: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        doc="Unique instance ID for this agent invocation (for log correlation).",
    )
    status: Mapped[AgentStatus] = mapped_column(
        SAEnum(AgentStatus, name="agent_status_enum", create_type=True),
        nullable=False,
        default=AgentStatus.IDLE,
        server_default=text("'idle'"),
    )
    # Timing
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    duration_ms: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )
    # Model used
    model_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        doc="Model identifier used by this agent (e.g. 'llama3.1:70b').",
    )
    prompt_version: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        doc="Prompt template version used (e.g. 'v2').",
    )
    # Token accounting
    prompt_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    completion_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    total_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Inputs and outputs
    input_data: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        doc="Serialised input context passed to this agent.",
    )
    output_data: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        doc="Serialised agent output.",
    )
    output_text: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Raw text output (for assistant / research agents).",
    )
    # Quality signals
    reflection_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        doc="Score from the Reflection Agent (0.0–1.0).",
    )
    reflection_critique: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Critique text from the Reflection Agent.",
    )
    confidence_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )
    debate_triggered: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        doc="True if this execution's output triggered the Debate Agent.",
    )
    # Error tracking
    retry_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_code: Mapped[str | None] = mapped_column(String(100), nullable=True)
    error_traceback: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Full traceback for FAILED executions (stored for debugging).",
    )
    # Retrieval context (for research / RAG agents)
    retrieved_chunk_ids: Mapped[list[str]] = mapped_column(
        ARRAY(String),
        nullable=False,
        default=list,
        server_default=text("'{}'"),
        doc="Qdrant point IDs of retrieved chunks used by this agent.",
    )
    retrieval_score_avg: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        doc="Average cross-encoder score of retrieved chunks.",
    )
    extra_data: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'"),
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    task: Mapped["AgentTask"] = relationship(
        "AgentTask",
        back_populates="executions",
    )
    retried_from: Mapped["AgentExecution | None"] = relationship(
        "AgentExecution",
        foreign_keys=[retry_of],
        remote_side="AgentExecution.id",
        doc="The execution that this is a retry of.",
    )
    tool_executions: Mapped[list["ToolExecution"]] = relationship(
        "ToolExecution",
        back_populates="agent_execution",
        cascade="all, delete-orphan",
        passive_deletes=True,
        doc="Tool calls made during this agent execution.",
    )

    def __repr__(self) -> str:
        return (
            f"<AgentExecution id={self.id} agent={self.agent_type} "
            f"step={self.step_index} status={self.status} "
            f"duration={self.duration_ms}ms>"
        )